### ISSUE TITLE
What do these do?

### ISSUE THREAD

**Issue by ICanNomNoms** [SCCapstone/TheB-Team#107]
In the calculations page I am not sure what these are for.

<img width="502" alt="what" src="https://user-images.githubusercontent.com/44646798/162228460-12cc2089-384e-48c0-819b-7232301a8f1b.PNG">

**Comment by josemvidal** [comment]
I've figured it out. You have to login as the admin (see Release Notes) then we can edit the rules.

Looks like we can create rules which then get applied in the Calculator:

https://user-images.githubusercontent.com/228704/162232653-52dfbd71-fa9e-4091-885d-8c2b930db1b0.mp4
