### ISSUE TITLE
What Does A and B mean?

### ISSUE THREAD

**Issue by johnburton0517** [SCCapstone/TheB-Team#111]
What are the values A and B? There is no description for what they are. And what are the units?

![image](https://user-images.githubusercontent.com/71100259/162635469-21cbf9c1-37b2-45b5-b02b-d7fa87a17f34.png)

**Comment by bcarter98** [comment]
A and B were units that someone went in and created in the rules section using the admin login. The admin will typically only make rules with values for variables such as length, width, height, and so on, but we gave the login for it just to show that the admin was able to change the rules if need be.
