### ISSUE TITLE
Spacing on Estimated Driving Time

### ISSUE THREAD

**Issue by FullmetalHero** [SCCapstone/TheB-Team#118]
![Issue02](https://user-images.githubusercontent.com/70229127/163730923-67627aab-ad9b-458f-8dba-6a7764094c05.JPG)
![Issue01](https://user-images.githubusercontent.com/70229127/163730927-fb08583c-2a0f-4fa7-ac04-b6a7992b04d0.JPG)

Spacing is a bit weird on these dialogues, maybe should be adjusted. Needs a space after the hour abbreviation, also should use 2h 50m rather than 2:50h as that is not an actual value in hours. Also the period is not needed after the h for the hour abbreviation.

**Comment by bcarter98** [comment]
3f3389c9e4694381f9e69f748ada54899d73419d

I was able to fix the spacing. However, there is no way that I can see to fix the wording of the times. It is reading in the data from the the routing API and that is how they word the times.
