### ISSUE TITLE
Map not integrated into app

### ISSUE THREAD

**Issue by josemvidal** [SCCapstone/TheB-Team#28]
The map is just a third-party iframe. It is not integrated into the app. The map should be pre-populated with information from your database.

![image](https://user-images.githubusercontent.com/228704/144855451-05aea652-4746-4e61-82ee-d4f2acd32f3a.png)

**Comment by josemvidal** [comment]
Right. I am just pointing out that embedding a third-party map into a website is not programming. If you want the maps to be a feature then you have to integrate it. Otherwise, #6 is not a real feature.

I assumed #6 was a real feature. I guess, you are just gonna iframe it? If so, don't even bother mentioning as a feature.

**Comment by LiamAOlson** [comment]
Okay thank you for the clarification.
