### ISSUE TITLE
Readme says /test/unit but no such folder exists

### ISSUE THREAD

**Issue by josemvidal** [SCCapstone/TheB-Team#40]
![image](https://user-images.githubusercontent.com/228704/151830620-aa630f06-7917-4698-99ae-8f263d7adb42.png)

![image](https://user-images.githubusercontent.com/228704/151830588-72ce24e2-9394-48c5-8a3b-704096e95bd9.png)

**Comment by bcarter98** [comment]
added a unit folder

**Comment by josemvidal** [comment]
When you close an issue by writing code, either fixing a bug or creating a new feature, you should add a link to the git-commit(s) that did it.

This can be done automatically if you just write "closes #X" in the comment of the git-commit, where X is the issue number you want to close. See [linking pull requests to issues using keywords](https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) for more information, or [watch this video](https://youtu.be/WMykv2ZMyEQ).

You should also write "#X" on any commit that is for #X. See my [github tips list](https://capstone.cse.sc.edu/lecture/github-issues/#tips) for all the tips.
