### ISSUE TITLE
All Issues are open. You did nothing?

### ISSUE THREAD

**Issue by josemvidal** [SCCapstone/TheB-Team#65]
<img width="608" alt="image" src="https://user-images.githubusercontent.com/228704/156009717-02abeb10-47d4-463a-b8d1-9eaa4c97ee66.png">

If not, please learn to use Issues.

The way issues work is
- If you are are assigned to an issue, you have to do it.
- Once you do it, you close the issue with a comment or, preferably, a link to your solution.

You should re-watch my [teamwork lectures](https://capstone.cse.sc.edu/lecture/teamwork) where I explain all this and more. Please learn to use GitHub. Not using them correctly negatively affects your grade.

**Comment by josemvidal** [comment]
I see you closed all the Issues. You should have also come back here and told my you did that. Issues are for communication. This Issue is a question and the nice thing to do is to answer the question.

**Comment by bcarter98** [comment]
We went through and closed everything that has been done up to this point. Apologies for not responding here.

**Comment by josemvidal** [comment]
No problem. Thanks!
